openapi: '3.0.2'
info:
  title: GAH_Clinic API
  version: '1.0'
servers:
  - url: http://localhost:8000/
paths:
  /admin/:
    get:
      summary: Goes to the admin dashboard
      description: This endpoints allows you to go to the django admin dashboard.
      responses:
        '200':
          description: OK

  /login/:
    post:
      summary: Obtain JWT token
      description: This endpoint allows users to obtain a JWT token by providing valid credentials.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user.
                  example: userTeste
                password:
                  type: string
                  description: The password of the user.
                  example: lol123
              required:
                - username
                - password
      responses:
        '200':
          description: JWT token obtained successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                    description: The access token (JWT) used for authentication.
                  user:
                    type: string
                    description: The username of the user
                  userId:
                    type: integer
                    description: The user ID
        '401':
          description: Invalid credentials
  /book-appointment/:
    post:
      summary: Book an appointment
      description: This endpoint allows a user to book an appointment with a doctor based on a specialty, doctor, date, and time.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                specialty:
                  type: string
                  description: The specialty of the doctor required for the appointment.
                  example: "Massagem"
                doctorId:
                  type: integer
                  description: The identifier for the doctor with whom the appointment is to be booked.
                  example: 1
                date:
                  type: string
                  format: date
                  description: The date when the appointment is scheduled.
                  example: "2024-04-20"
                time:
                  type: string
                  format: time
                  description: The time when the appointment starts, must be on the hour (e.g., 14:00).
                  example: "15:00"
      responses:
        '201':
          description: Appointment booked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the request
                    example: success
                  appointment_id:
                    type: integer
                    description: The unique identifier of the booked appointment.
                    example: 1234
                  message:
                    type: string
                    description: A message confirming the successful booking of the appointment.
                    example: "Appointment booked successfully."
        '400':
          description: Bad request, invalid input data
        '401':
          description: Unauthorized, token missing or invalid
        '404':
          description: No record found for the specified doctorId. Please check the doctorId and try again.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "No record found for the specified doctorId. Please check the doctorId and try again."
                    example: "Doctor does not exist."
        '409':
          description: Conflict, an appointment already exists at this date and time
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating a conflict with an existing appointment.
                    example: "An appointment already exists at this date and time."
        '500':
          description: Internal Server Error
  /payment/:
    post:
      summary: Process payment for a booked appointment
      description: This endpoint processes payments for appointments and must be completed within 30 minutes of booking.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                appointment_id:
                  type: string
                  description: The identifier of the booked appointment.
                  example: uniqueId1
      responses:
        '200':
          description: Payment processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the payment process.
                    example: "Success"
                  message:
                    type: string
                    description: A message detailing the result of the payment operation.
                    example: "Payment has been processed successfully."
        '400':
          description: Payment processing failed
        '401':
          description: Unauthorized, token missing or invalid
        '409':
          description: Payment already made
        '500':
          description: Internal Server Error
  /user/appointments/:
    get:
      summary: Retrieve all appointments for the authenticated user
      description: This endpoint retrieves all appointments associated with the authenticated user. It requires JWT authentication.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved all appointments for the user.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    appointment_id:
                      type: integer
                      description: The unique identifier of the appointment
                      example: 1234
                    date:
                      type: string
                      format: date
                      description: The date of the appointment
                      example: "2024-04-20"
                    time:
                      type: string
                      format: time
                      description: The time of the appointment.
                      example: "15:00:00"
                    specialty:
                      type: string
                      description: The medical specialty of the appointment.
                      example: "Dermatology"
                    doctorId:
                      type: integer
                      description: The identifier of the doctor
                      example: 1
                    status:
                      type: string
                      description: The current status of the appointment.
                      example: "scheduled"
                      enum:
                        - waiting for payment
                        - scheduled
                        - finished
                    doctorName:
                      type: string
                      description: The name of the doctor
                      example: "Maria Filho"
                maxItems: 7
        '401':
          description: Unauthorized, token missing or invalid
        '500':
          description: Internal Server Error
  /appointments/{appointment_id}/status:
    get:
      summary: Retrieve the status of an appointment
      description: This endpoint allows a user to retrieve the current status of a specific appointment by providing the appointment's unique identifier.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: appointment_id
          required: true
          schema:
            type: string
          description: The unique identifier of the appointment for which to retrieve the status.
      responses:
        '200':
          description: Successfully retrieved the status of the appointment.
          content:
            application/json:
              schema:
                type: object
                properties:
                  appointment_id:
                    type: string
                    description: The unique identifier of the appointment.
                    example: "abc123"
                  status:
                    type: string
                    description: The current status of the appointment.
                    example: "waiting for payment"
                    enum:
                      - waiting for payment
                      - scheduled
                      - finished
        '400':
          description: Bad request, invalid appointment ID
        '401':
          description: Unauthorized, token missing or invalid
        '404':
          description: Not found, appointment not found
        '500':
          description: Internal Server Error
  /doctors/:
    get:
      summary: Retrieve a list of all doctors
      description: This endpoint retrieves a list of all doctors available in the clinic.
      responses:
        '200':
          description: Successfully retrieved the list of doctors.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the request.
                    example: success
                  doctors:
                    type: array
                    items:
                      type: object
                      properties:
                        doctorId:
                          type: integer
                          description: The unique identifier of the doctor
                          example: 1
                        doctorName:
                          type: string
                          description: The name of the doctor
                          example: "Maria Filho"
                        specialty:
                          type: string
                          description: The specialty of the doctor
                          example: "Dermatology"
        '400':
          description: Failed to retrieve the list of doctors
        '500':
          description: Internal Server Error
  /clinic-login/:
    post:
      summary: Authenticate user via face recognition
      description: This endpoint authenticates a user via face recognition by providing a base64 encoded image.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
                  description: Base64 encoded image of the user.
                  example: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD..."
      responses:
        '200':
          description: Successfully authenticated and logged in.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message indicating successful login.
                    example: "Entered in the clinic successfully"
                  user_id:
                    type: integer
                    description: The unique identifier of the user.
                    example: 123
        '400':
          description: Bad request, invalid image data
        '404':
          description: Not found, user not found
        '500':
          description: Internal Server Error
  /finish-appointment/:
    post:
      summary: Finish an appointment
      description: This endpoint finishes an appointment by providing the appointment ID and user ID.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                appointmentId:
                  type: integer
                  description: The identifier of the appointment to finish.
                  example: 1234
                userId:
                  type: integer
                  description: The identifier of the user finishing the appointment.
                  example: 1
      responses:
        '200':
          description: Successfully finished the appointment.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the request.
                    example: success
                  message:
                    type: string
                    description: A message indicating the appointment has been finished.
                    example: "Appointment cancelled successfully."
        '400':
          description: Bad request, invalid input data
        '401':
          description: Unauthorized, token missing or invalid
        '500':
          description: Internal Server Error
  /doctor/{doctor_id}/appointments:
    get:
      summary: Retrieve all appointments for a specific doctor
      description: This endpoint retrieves all appointments associated with a specific doctor by providing the doctor's unique identifier.
      parameters:
        - in: path
          name: doctor_id
          required: true
          schema:
            type: integer
          description: The unique identifier of the doctor for whom to retrieve the appointments.
      responses:
        '200':
          description: Successfully retrieved all appointments for the doctor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the request.
                    example: success
                  appointments:
                    type: array
                    items:
                      type: object
                      properties:
                        appointment_id:
                          type: integer
                          description: The unique identifier of the appointment
                          example: 1234
                        date:
                          type: string
                          format: date
                          description: The date of the appointment
                          example: "2024-04-20"
                        time:
                          type: string
                          format: time
                          description: The time of the appointment.
                          example: "15:00:00"
                        specialty:
                          type: string
                          description: The medical specialty of the appointment.
                          example: "Dermatology"
                        doctorId:
                          type: integer
                          description: The identifier of the doctor
                          example: 1
                        status:
                          type: string
                          description: The current status of the appointment.
                          example: "scheduled"
                          enum:
                            - waiting for payment
                            - scheduled
                            - finished
        '400':
          description: Failed to retrieve appointments
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
